import 'package:flutter/foundation.dart';
import '../models/models.dart';

class InternationalService {
  /// 6/7 修复：按 userType × scene 分桶返回 24 种国际内容
  /// 每个 key 至少 4-6 条
  Future<List<ContentItem>> getRecommendations(UserType userType, Scene scene) async {
    final key = '${userType.bucketKey}_${scene.bucketKey}'; // 6/9 修复：同 news_service.dart
    return _allContent[key] ?? _fallback(userType, scene);
  }

  Future<List<ContentItem>> search(String query) async {
    if (query.trim().isEmpty) return [];
    final q = query.toLowerCase();
    final results = <ContentItem>[];
    for (final list in _allContent.values) {
      for (final item in list) {
        if (item.title.toLowerCase().contains(q)) {
          results.add(item);
        }
      }
    }
    return results;
  }

  List<ContentItem> _fallback(UserType u, Scene s) {
    return [
      ContentItem(
        id: 'intl_fallback_${u.name}_${s.name}',
        title: '${u.name} · ${s.name}',
        description: 'International content for you.',
        duration: '5min',
        source: 'FragmentTime',
        sourceType: ContentSource.rss,
        contentType: ContentType.card,
        priceType: ContentPriceType.free,
      ),
    ];
  }

  static final Map<String, List<ContentItem>> _allContent = {
    'student_learn': [
      ContentItem(id: 'intl_student_learn_1', title: 'Khan Academy - Human Anatomy', description: '12-min intro', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '8jLOx1hD3_o', videoPlatform: VideoPlatform.youtube, duration: '12min', externalUrl: 'https://youtube.com/watch?v=8jLOx1hD3_o', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_learn_2', title: 'freeCodeCamp - Python Tutorial', description: '4h+ course', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'rfscVS0vtbw', videoPlatform: VideoPlatform.youtube, duration: '4h', externalUrl: 'https://youtube.com/watch?v=rfscVS0vtbw', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_learn_3', title: 'Crash Course - World History', description: '10 min episodes', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '5qap5aO4i9A', videoPlatform: VideoPlatform.youtube, duration: '10min', externalUrl: 'https://youtube.com/watch?v=5qap5aO4i9A', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_learn_4', title: 'TED-Ed - Quick Lessons', description: '5 min each', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DWcJFNfaw9c', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=DWcJFNfaw9c', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_learn_5', title: '3Blue1Brown - Math', description: 'Visual math', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'HluANRwPyNo', videoPlatform: VideoPlatform.youtube, duration: '10min', externalUrl: 'https://youtube.com/watch?v=HluANRwPyNo', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_learn_6', title: 'Kurzgesagt - Science', description: 'Animated science', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'wupToqz1e2g', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=wupToqz1e2g', priceType: ContentPriceType.free),
    ],
    'student_listen': [
      ContentItem(id: 'intl_student_listen_1', title: 'BBC Learning English', description: '5 min daily', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=BBC%20Learning%20Eng', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_listen_2', title: 'NPR Short Story', description: '5 min', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=NPR%20Short%20Story', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_listen_3', title: 'Science Friday', description: '5 min highlights', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Science%20Friday', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_listen_4', title: 'History Extra', description: '5 min story', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=History%20Extra', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_listen_5', title: 'The Daily - NYT', description: '20 min', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '20min', externalUrl: 'https://podcasts.apple.com/cn/search?term=The%20Daily%20-%20NYT', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_listen_6', title: 'TED Talks Daily', description: '5-10 min', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '8min', externalUrl: 'https://podcasts.apple.com/cn/search?term=TED%20Talks%20Daily', priceType: ContentPriceType.free),
    ],
    'student_relax': [
      ContentItem(id: 'intl_student_relax_1', title: '5-min Calm Breathing', description: 'For exam stress', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'ZSt9tm7RoUU', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=ZSt9tm7RoUU', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_relax_2', title: '5-min Body Scan', description: 'Quick reset', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DKbzSrt_PXw', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=DKbzSrt_PXw', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_relax_3', title: 'White Noise - 5 min', description: 'Focus background', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=White%20Noise%20-%205%20', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_relax_4', title: '5-min Box Breathing', description: 'Navy SEAL method', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '8jLOx1hD3_o', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=8jLOx1hD3_o', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_relax_5', title: 'Mindful Walk - 5 min', description: 'Outside', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'rfscVS0vtbw', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=rfscVS0vtbw', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_relax_6', title: 'Journaling Prompt - 5 min', description: 'Clear your head', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Journaling%20Promp', priceType: ContentPriceType.free),
    ],
    'student_workout': [
      ContentItem(id: 'intl_student_workout_1', title: 'Classroom 5-min Stretch', description: '5 moves', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '5qap5aO4i9A', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=5qap5aO4i9A', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_workout_2', title: '5-min Cardio Blast', description: 'At home', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DWcJFNfaw9c', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=DWcJFNfaw9c', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_workout_3', title: '5-min Yoga for Teens', description: 'Basic', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'HluANRwPyNo', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=HluANRwPyNo', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_workout_4', title: '5-min Eye Yoga', description: 'Prevent myopia', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'wupToqz1e2g', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=wupToqz1e2g', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_workout_5', title: '5-min Wrist Stretches', description: 'For writers', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'ZSt9tm7RoUU', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=ZSt9tm7RoUU', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_student_workout_6', title: '5-min Posture Fix', description: 'For desk', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DKbzSrt_PXw', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=DKbzSrt_PXw', priceType: ContentPriceType.free),
    ],

    'officeWorker_learn': [
      ContentItem(id: 'intl_officeWorker_learn_1', title: 'Deep Work - 5 min summary', description: 'Cal Newport method', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Deep%20Work%20-%205%20mi', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_learn_2', title: 'Lex Fridman - AI Safety', description: 'Long-form interview', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '90min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Lex%20Fridman%20AI%20Safety', priceType: ContentPriceType.membership, priceNote: 'Free with ads'),
      ContentItem(id: 'intl_officeWorker_learn_3', title: 'HBR IdeaCast - 5 min', description: 'Harvard Business', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=HBR%20IdeaCast%20-%205', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_learn_4', title: 'TED Business - 5 min', description: 'Curated', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=TED%20Business%20-%205', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_learn_5', title: 'The Tim Ferriss Show', description: '5 min highlights', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=The%20Tim%20Ferriss%20', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_learn_6', title: 'How I Built This - 5 min', description: 'NPR / Guy Raz', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=How%20I%20Built%20This', priceType: ContentPriceType.free),
    ],
    'officeWorker_listen': [
      ContentItem(id: 'intl_officeWorker_listen_1', title: 'The Daily - Top News', description: 'NYT 20 min', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '20min', externalUrl: 'https://podcasts.apple.com/the-daily', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_listen_2', title: 'WSJ What\'s News', description: '5 min', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_listen_3', title: 'BBC Global News', description: '5 min podcast', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=BBC%20Global%20News', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_listen_4', title: 'Marketplace - 5 min', description: 'NPR business', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Marketplace%20-%205%20', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_listen_5', title: 'Tech News Today', description: '5 min', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Tech%20News%20Today', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_listen_6', title: 'The Hustle - 5 min', description: 'Business + tech', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=The%20Hustle%20-%205%20m', priceType: ContentPriceType.free),
    ],
    'officeWorker_relax': [
      ContentItem(id: 'intl_officeWorker_relax_1', title: 'Lunch Break Mindfulness', description: '5 min calm', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Lunch%20Break%20Mind', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_relax_2', title: '5-min Office Meditation', description: 'Headphones-friendly', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '8jLOx1hD3_o', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=8jLOx1hD3_o', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_relax_3', title: '5-min White Noise', description: 'Focus background', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=5-min%20White%20Nois', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_relax_4', title: 'Box Breathing - 5 min', description: 'Reset', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'rfscVS0vtbw', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=rfscVS0vtbw', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_relax_5', title: '5-min Walk Meditation', description: 'Outside', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '5qap5aO4i9A', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=5qap5aO4i9A', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_relax_6', title: 'Body Scan - 5 min', description: 'Quick reset', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Body%20Scan%20-%205%20mi', priceType: ContentPriceType.free),
    ],
    'officeWorker_workout': [
      ContentItem(id: 'intl_officeWorker_workout_1', title: 'Desk Worker 5-min Stretch', description: 'Neck + shoulders', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DWcJFNfaw9c', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=DWcJFNfaw9c', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_workout_2', title: '5-min Lower Back', description: 'Sedentary fix', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'HluANRwPyNo', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=HluANRwPyNo', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_workout_3', title: '5-min Wrist Care', description: 'Anti-Carpal', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'wupToqz1e2g', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=wupToqz1e2g', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_workout_4', title: '5-min Standing Workout', description: 'Meeting break', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'ZSt9tm7RoUU', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=ZSt9tm7RoUU', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_workout_5', title: '5-min Eye Routine', description: 'Screen fatigue', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DKbzSrt_PXw', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=DKbzSrt_PXw', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_officeWorker_workout_6', title: '5-min Posture Reset', description: 'Sit better', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '8jLOx1hD3_o', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=8jLOx1hD3_o', priceType: ContentPriceType.free),
    ],

    'entrepreneur_learn': [
      ContentItem(id: 'intl_entrepreneur_learn_1', title: 'Y Combinator - Startup School', description: '5 min core concept', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'rfscVS0vtbw', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=rfscVS0vtbw', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_learn_2', title: 'a16z Podcast - 5 min', description: 'Tech trends', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=a16z%20Podcast%20-%205', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_learn_3', title: 'How I Built This', description: 'Founder stories', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=How%20I%20Built%20This', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_learn_4', title: 'Masters of Scale - 5 min', description: 'Reid Hoffman', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Masters%20of%20Scale', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_learn_5', title: 'SaaS Strats - 5 min', description: 'B2B founder', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=SaaS%20Strats%20-%205%20', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_learn_6', title: 'The Pitch - 5 min', description: 'Investor pitches', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=The%20Pitch%20-%205%20mi', priceType: ContentPriceType.free),
    ],
    'entrepreneur_listen': [
      ContentItem(id: 'intl_entrepreneur_listen_1', title: 'a16z Podcast', description: 'Tech + business', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '30min', externalUrl: 'https://podcasts.apple.com/cn/search?term=a16z%20Podcast', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_listen_2', title: 'TechCrunch Radio - 5 min', description: 'Daily startup news', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=TechCrunch%20Radio', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_listen_3', title: 'Bloomberg Tech - 5 min', description: 'Daily tech + markets', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Bloomberg%20Tech%20-', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_listen_4', title: 'The Information - 5 min', description: 'Tech deep dive', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=The%20Information%20', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_listen_5', title: 'Stratechery - 5 min', description: 'Ben Thompson', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Stratechery%20-%205%20', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_listen_6', title: 'Acquired - 5 min', description: 'Company histories', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Acquired%20-%205%20min', priceType: ContentPriceType.free),
    ],
    'entrepreneur_relax': [
      ContentItem(id: 'intl_entrepreneur_relax_1', title: 'Founder Burnout Recovery', description: '5 min reset', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '5qap5aO4i9A', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=5qap5aO4i9A', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_relax_2', title: '5-min Decision Reset', description: 'CBT method', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DWcJFNfaw9c', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=DWcJFNfaw9c', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_relax_3', title: '5-min Power Nap Guide', description: 'For CEOs', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=5-min%20Power%20Nap%20', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_relax_4', title: '5-min Energy Boost', description: 'Reset', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'HluANRwPyNo', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=HluANRwPyNo', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_relax_5', title: '5-min Mental Walk', description: 'Out of office', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'wupToqz1e2g', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=wupToqz1e2g', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_relax_6', title: '5-min CEO Meditation', description: 'Board calm', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=5-min%20CEO%20Medita', priceType: ContentPriceType.free),
    ],
    'entrepreneur_workout': [
      ContentItem(id: 'intl_entrepreneur_workout_1', title: 'Hotel Room 5-min Workout', description: 'No equipment', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'ZSt9tm7RoUU', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=ZSt9tm7RoUU', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_workout_2', title: '5-min Founder Fitness', description: 'Busy schedule', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DKbzSrt_PXw', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=DKbzSrt_PXw', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_workout_3', title: '5-min Neck & Shoulders', description: 'Computer neck', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '8jLOx1hD3_o', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=8jLOx1hD3_o', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_workout_4', title: '5-min Pre-Meeting Pump', description: 'Coffee alternative', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'rfscVS0vtbw', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=rfscVS0vtbw', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_workout_5', title: '5-min Eye Routine', description: 'Screen fatigue', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '5qap5aO4i9A', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=5qap5aO4i9A', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_entrepreneur_workout_6', title: '5-min Seated Workout', description: 'On a plane', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DWcJFNfaw9c', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=DWcJFNfaw9c', priceType: ContentPriceType.free),
    ],

    'parent_learn': [
      ContentItem(id: 'intl_parent_learn_1', title: 'How to Talk So Kids Listen', description: '5 min summary', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=How%20to%20Talk%20So%20K', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_learn_2', title: 'Positive Discipline - 5 min', description: 'Jane Nelsen', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Positive%20Discipl', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_learn_3', title: 'Raising Good Humans', description: 'Dr. Aliza', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Raising%20Good%20Hum', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_learn_4', title: 'The Mom Hour', description: '5 min mom tips', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=The%20Mom%20Hour', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_learn_5', title: 'Screen Time Tips - 5 min', description: 'Family tech', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Screen%20Time%20Tips', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_learn_6', title: 'Co-Parenting - 5 min', description: 'Divorced parents', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Co-Parenting%20-%205', priceType: ContentPriceType.free),
    ],
    'parent_listen': [
      ContentItem(id: 'intl_parent_listen_1', title: 'Bedtime Story for Kids', description: '5 min', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Bedtime%20Story%20fo', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_listen_2', title: 'Sesame Street Podcast', description: '5 min', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Sesame%20Street%20Po', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_listen_3', title: 'Story Time - 5 min', description: 'Kids', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Story%20Time%20-%205%20m', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_listen_4', title: 'Classical for Kids', description: '5 min', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Classical%20for%20Ki', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_listen_5', title: 'Lullaby - 5 min', description: 'Bedtime', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Lullaby%20-%205%20min', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_listen_6', title: 'ABC Phonics - 5 min', description: 'Learn letters', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=ABC%20Phonics%20-%205%20', priceType: ContentPriceType.free),
    ],
    'parent_relax': [
      ContentItem(id: 'intl_parent_relax_1', title: '5-min Mom Recharge', description: 'Breathe + reset', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'HluANRwPyNo', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=HluANRwPyNo', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_relax_2', title: '5-min Nap-time Calm', description: 'For moms', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=5-min%20Nap-time%20C', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_relax_3', title: '5-min Guilt Release', description: 'CBT method', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'wupToqz1e2g', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=wupToqz1e2g', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_relax_4', title: '5-min Body Scan', description: 'Quick reset', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'ZSt9tm7RoUU', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=ZSt9tm7RoUU', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_relax_5', title: '5-min Me-Time', description: 'Reclaim yourself', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DKbzSrt_PXw', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=DKbzSrt_PXw', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_relax_6', title: '5-min Dad Self-care', description: 'For fathers', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=5-min%20Dad%20Self-c', priceType: ContentPriceType.free),
    ],
    'parent_workout': [
      ContentItem(id: 'intl_parent_workout_1', title: '5-min Living Room Workout', description: 'With kids around', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '8jLOx1hD3_o', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=8jLOx1hD3_o', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_workout_2', title: '5-min Postpartum Core', description: 'For new moms', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'rfscVS0vtbw', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=rfscVS0vtbw', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_workout_3', title: '5-min Stroller Workout', description: 'Outside', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '5qap5aO4i9A', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=5qap5aO4i9A', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_workout_4', title: '5-min Back Recovery', description: 'From carrying', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DWcJFNfaw9c', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=DWcJFNfaw9c', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_workout_5', title: '5-min Dad Strength', description: 'Tone arms', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'HluANRwPyNo', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=HluANRwPyNo', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_parent_workout_6', title: '5-min Family Yoga', description: 'Together', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'wupToqz1e2g', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=wupToqz1e2g', priceType: ContentPriceType.free),
    ],

    'senior_learn': [
      ContentItem(id: 'intl_senior_learn_1', title: 'Managing High Blood Pressure', description: '5 min guide', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'ZSt9tm7RoUU', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=ZSt9tm7RoUU', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_learn_2', title: 'Knee Health - Daily Stretches', description: 'Doctor recommended', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DKbzSrt_PXw', videoPlatform: VideoPlatform.youtube, duration: '8min', externalUrl: 'https://youtube.com/watch?v=DKbzSrt_PXw', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_learn_3', title: 'Bone Health 101 - 5 min', description: 'Osteoporosis prevention', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '8jLOx1hD3_o', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=8jLOx1hD3_o', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_learn_4', title: 'Reading Medical Reports', description: '5 min guide', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'rfscVS0vtbw', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=rfscVS0vtbw', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_learn_5', title: 'Sleep Better - 5 min', description: 'For seniors', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '5qap5aO4i9A', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=5qap5aO4i9A', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_learn_6', title: 'Brain Health 5 min', description: 'Prevent dementia', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DWcJFNfaw9c', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=DWcJFNfaw9c', priceType: ContentPriceType.free),
    ],
    'senior_listen': [
      ContentItem(id: 'intl_senior_listen_1', title: 'Today in History', description: '5 min daily', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Today%20in%20History', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_listen_2', title: 'Classic Hits - 5 min', description: 'Oldies', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Classic%20Hits%20-%205', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_listen_3', title: 'BBC News 5 min', description: 'Daily brief', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=BBC%20News%205%20min', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_listen_4', title: 'Health Tips 5 min', description: 'Mayo Clinic', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Health%20Tips%205%20mi', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_listen_5', title: 'NPR Fresh Air - 5 min', description: 'Highlights', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=NPR%20Fresh%20Air%20-%20', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_listen_6', title: 'Storytellers - 5 min', description: 'True stories', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Storytellers%20-%205', priceType: ContentPriceType.free),
    ],
    'senior_relax': [
      ContentItem(id: 'intl_senior_relax_1', title: 'Gentle 5-min Breathing', description: 'Calm guide', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'HluANRwPyNo', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=HluANRwPyNo', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_relax_2', title: '5-min Nature Sounds', description: 'Birds + water', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=5-min%20Nature%20Sou', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_relax_3', title: '5-min Sleep Calm', description: 'Insomnia aid', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=5-min%20Sleep%20Calm', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_relax_4', title: '5-min Tai Chi Breathing', description: 'TCM', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'wupToqz1e2g', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=wupToqz1e2g', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_relax_5', title: '5-min Meditation Intro', description: 'Senior edition', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'ZSt9tm7RoUU', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=ZSt9tm7RoUU', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_relax_6', title: '5-min Garden Meditation', description: 'Outside', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DKbzSrt_PXw', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=DKbzSrt_PXw', priceType: ContentPriceType.free),
    ],
    'senior_workout': [
      ContentItem(id: 'intl_senior_workout_1', title: 'Gentle Stretch - 5 Moves', description: '1 min each', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '8jLOx1hD3_o', videoPlatform: VideoPlatform.youtube, duration: '8min', externalUrl: 'https://youtube.com/watch?v=8jLOx1hD3_o', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_workout_2', title: 'Tai Chi 5-min Intro', description: '24 forms', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'rfscVS0vtbw', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=rfscVS0vtbw', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_workout_3', title: 'Qigong 5-min', description: 'TCM tradition', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '5qap5aO4i9A', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=5qap5aO4i9A', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_workout_4', title: 'Joint Mobility 5-min', description: 'All joints', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DWcJFNfaw9c', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=DWcJFNfaw9c', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_workout_5', title: 'Walking 5-min', description: 'Daily cardio', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'HluANRwPyNo', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=HluANRwPyNo', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_senior_workout_6', title: 'Chair Exercises 5-min', description: 'No equipment', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'wupToqz1e2g', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=wupToqz1e2g', priceType: ContentPriceType.free),
    ],

    'child_learn': [
      ContentItem(id: 'intl_child_learn_1', title: 'Why is the sky blue?', description: '5 min science for kids', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'ZSt9tm7RoUU', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=ZSt9tm7RoUU', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_learn_2', title: 'Dancing Raisins - Easy Science', description: 'Home experiment', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DKbzSrt_PXw', videoPlatform: VideoPlatform.youtube, duration: '3min', externalUrl: 'https://youtube.com/watch?v=DKbzSrt_PXw', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_learn_3', title: 'Why do we dream?', description: '5 min', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '8jLOx1hD3_o', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=8jLOx1hD3_o', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_learn_4', title: 'How do birds fly?', description: '5 min science', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'rfscVS0vtbw', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=rfscVS0vtbw', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_learn_5', title: 'Where does rain come from?', description: 'Water cycle', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '5qap5aO4i9A', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=5qap5aO4i9A', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_learn_6', title: 'Why is the ocean salty?', description: '5 min', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DWcJFNfaw9c', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=DWcJFNfaw9c', priceType: ContentPriceType.free),
    ],
    'child_listen': [
      ContentItem(id: 'intl_child_listen_1', title: 'Bedtime Story - Little Bear', description: '5 min', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Bedtime%20Story%20-%20', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_listen_2', title: 'Sesame Street - 5 min', description: 'Classic', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Sesame%20Street%20-%20', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_listen_3', title: 'Fairy Tales - 5 min', description: 'Classic', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Fairy%20Tales%20-%205%20', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_listen_4', title: 'Kids Song - 5 min', description: 'Sing along', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Kids%20Song%20-%205%20mi', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_listen_5', title: 'Animal Stories - 5 min', description: 'Fun', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Animal%20Stories%20-', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_listen_6', title: 'ABC Songs - 5 min', description: 'Learn letters', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=ABC%20Songs%20-%205%20mi', priceType: ContentPriceType.free),
    ],
    'child_relax': [
      ContentItem(id: 'intl_child_relax_1', title: 'Flying on Clouds - 5 min', description: 'Gentle imagination', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'HluANRwPyNo', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=HluANRwPyNo', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_relax_2', title: '5-min Test Calm', description: 'For exam', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'wupToqz1e2g', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=wupToqz1e2g', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_relax_3', title: 'Bedtime Story - 5 min', description: 'Soothing', source: 'Apple Podcasts', sourceType: ContentSource.applePodcasts, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://podcasts.apple.com/cn/search?term=Bedtime%20Story%20-%20', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_relax_4', title: '5-min Worry Box', description: 'CBT for kids', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'ZSt9tm7RoUU', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=ZSt9tm7RoUU', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_relax_5', title: '5-min Rainbow Breath', description: 'Visualization', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DKbzSrt_PXw', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=DKbzSrt_PXw', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_relax_6', title: '5-min Gratitude Journal', description: 'For kids', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '8jLOx1hD3_o', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=8jLOx1hD3_o', priceType: ContentPriceType.free),
    ],
    'child_workout': [
      ContentItem(id: 'intl_child_workout_1', title: '5-min Play Break', description: 'Safe moves', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'rfscVS0vtbw', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=rfscVS0vtbw', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_workout_2', title: '5-min Jump Rope', description: 'PE class', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: '5qap5aO4i9A', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=5qap5aO4i9A', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_workout_3', title: '5-min PE Workout', description: 'At home', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'DWcJFNfaw9c', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=DWcJFNfaw9c', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_workout_4', title: '5-min Eye Yoga', description: 'Myopia prevention', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'HluANRwPyNo', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=HluANRwPyNo', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_workout_5', title: '5-min Kids Dance', description: 'Fun', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'wupToqz1e2g', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=wupToqz1e2g', priceType: ContentPriceType.free),
      ContentItem(id: 'intl_child_workout_6', title: '5-min Posture Yoga', description: 'Anti-hunch', source: 'YouTube', sourceType: ContentSource.youtube, contentType: ContentType.video, videoId: 'ZSt9tm7RoUU', videoPlatform: VideoPlatform.youtube, duration: '5min', externalUrl: 'https://youtube.com/watch?v=ZSt9tm7RoUU', priceType: ContentPriceType.free),
    ],
  };
}
