import 'package:flutter/foundation.dart';
import '../models/models.dart';

class NewsService {
  /// 6/7 修复：按 userType × scene 分桶返回 24 种内容
  /// 不分桶 = 儿童/上班族/退休都看到同样的 = 宪法 §6 违规
  /// 6/9 修复：用 bucketKey（enum 标识符）而不是 .name（"Office Worker" 带空格），
  /// 否则 key="Office Worker_Learn" 永远对不上 _allContent 里的 "officeWorker_learn"
  Future<List<ContentItem>> getRecommendations(UserType userType, Scene scene) async {
    final key = '${userType.bucketKey}_${scene.bucketKey}';
    return _allContent[key] ?? _fallback(userType, scene);
  }

  Future<List<ContentItem>> search(String query) async {
    if (query.trim().isEmpty) return [];
    final q = query.toLowerCase();
    final results = <ContentItem>[];
    for (final list in _allContent.values) {
      for (final item in list) {
        if (item.title.toLowerCase().contains(q) ||
            (item.description?.toLowerCase().contains(q) ?? false)) {
          results.add(item);
        }
      }
    }
    return results;
  }

  List<ContentItem> _fallback(UserType u, Scene s) {
    return [
      ContentItem(
        id: 'fallback_${u.name}_${s.name}',
        title: '${u.title} · ${s.title}',
        description: '为你推荐的通用内容。完整版等你告诉小 O 想要的类型。',
        duration: '5min',
        source: 'fragment_time',
        sourceType: ContentSource.news36kr,
        contentType: ContentType.card,
        priceType: ContentPriceType.free,
      ),
    ];
  }

  // 6 角色 × 4 场景 = 24 种推荐，每个 key 至少 4-6 条
  // 6/7 §10 验：24/24 keys 都非空
  static final Map<String, List<ContentItem>> _allContent = {
    // 学生 (4-6 条/key)
    'student_learn': [
      ContentItem(id: 'student_learn_1', title: '用 5 分钟搞懂：什么是"光合作用"？', description: '初中生物核心概念', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E7%94%A8%205%20%E5%88%86%E9%92%9F%E6%90%9E%E6%87%82%EF%BC%9A%E4%BB%80%E4%B9%88%E6%98%AF%E5%85%89%E5%90%88%E4%BD%9C%E7%94%A8', priceType: ContentPriceType.free),
      ContentItem(id: 'student_learn_2', title: '高考数学：3 道经典函数题', description: '5 分钟学会解题套路', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '8min', externalUrl: 'https://search.bilibili.com/all?keyword=%E9%AB%98%E8%80%83%E6%95%B0%E5%AD%A6%EF%BC%9A3%20%E9%81%93%E7%BB%8F%E5%85%B8%E5%87%BD%E6%95%B0%E9%A2%98', priceType: ContentPriceType.free),
      ContentItem(id: 'student_learn_3', title: '英语单词：10 个高频词根', description: '记住词根，单词量翻倍', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.card, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E8%8B%B1%E8%AF%AD%E5%8D%95%E8%AF%8D%EF%BC%9A10%20%E4%B8%AA%E9%AB%98%E9%A2%91%E8%AF%8D%E6%A0%B9', priceType: ContentPriceType.free),
      ContentItem(id: 'student_learn_4', title: '物理入门：牛顿 3 大定律', description: '5 分钟搞懂', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E7%89%A9%E7%90%86%E5%85%A5%E9%97%A8%EF%BC%9A%E7%89%9B%E9%A1%BF%203%20%E5%A4%A7%E5%AE%9A%E5%BE%8B', priceType: ContentPriceType.free),
      ContentItem(id: 'student_learn_5', title: '语文：5 分钟学一个修辞手法', description: '比喻/拟人/排比', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.card, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E8%AF%AD%E6%96%87%EF%BC%9A5%20%E5%88%86%E9%92%9F%E5%AD%A6%E4%B8%80%E4%B8%AA%E4%BF%AE%E8%BE%9E%E6%89%8B%E6%B3%95', priceType: ContentPriceType.free),
      ContentItem(id: 'student_learn_6', title: '历史：今天发生了什么？', description: '历史上的今天', source: '36氪', sourceType: ContentSource.news36kr, contentType: ContentType.card, duration: '3min', externalUrl: 'https://36kr.com/search/articles/%E5%8E%86%E5%8F%B2%EF%BC%9A%E4%BB%8A%E5%A4%A9%E5%8F%91%E7%94%9F%E4%BA%86%E4%BB%80%E4%B9%88%EF%BC%9F', priceType: ContentPriceType.free),
    ],
    'student_listen': [
      ContentItem(id: 'student_listen_1', title: '今日科普：3 个奇闻', description: '5 分钟听完', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E4%BB%8A%E6%97%A5%E7%A7%91%E6%99%AE%EF%BC%9A3%20%E4%B8%AA%E5%A5%87%E9%97%BB', priceType: ContentPriceType.free),
      ContentItem(id: 'student_listen_2', title: '睡前英语故事：5 分钟', description: 'English bedtime story', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E7%9D%A1%E5%89%8D%E8%8B%B1%E8%AF%AD%E6%95%85%E4%BA%8B%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'student_listen_3', title: '中学必背古诗：5 首', description: '早晚磨耳朵', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E4%B8%AD%E5%AD%A6%E5%BF%85%E8%83%8C%E5%8F%A4%E8%AF%97%EF%BC%9A5%20%E9%A6%96', priceType: ContentPriceType.free),
      ContentItem(id: 'student_listen_4', title: 'BBC 6 Minute English', description: '提升听力', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '6min', externalUrl: 'https://www.ximalaya.com/search/BBC%206%20Minute%20Eng', priceType: ContentPriceType.free),
      ContentItem(id: 'student_listen_5', title: '初中物理：声学入门', description: '5 分钟听懂', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E5%88%9D%E4%B8%AD%E7%89%A9%E7%90%86%EF%BC%9A%E5%A3%B0%E5%AD%A6%E5%85%A5%E9%97%A8', priceType: ContentPriceType.free),
      ContentItem(id: 'student_listen_6', title: '新概念英语：5 分钟一段', description: '经典教材', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E6%96%B0%E6%A6%82%E5%BF%B5%E8%8B%B1%E8%AF%AD%EF%BC%9A5%20%E5%88%86%E9%92%9F%E4%B8%80%E6%AE%B5', priceType: ContentPriceType.free),
    ],
    'student_relax': [
      ContentItem(id: 'student_relax_1', title: '考前 5 分钟放空练习', description: '深呼吸 + 身体扫描', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E8%80%83%E5%89%8D%205%20%E5%88%86%E9%92%9F%E6%94%BE%E7%A9%BA%E7%BB%83%E4%B9%A0', priceType: ContentPriceType.free),
      ContentItem(id: 'student_relax_2', title: '考试焦虑：5 分钟缓解', description: '心理学方法', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E8%80%83%E8%AF%95%E7%84%A6%E8%99%91%EF%BC%9A5%20%E5%88%86%E9%92%9F%E7%BC%93%E8%A7%A3', priceType: ContentPriceType.free),
      ContentItem(id: 'student_relax_3', title: '课间 5 分钟：白噪音 + 闭眼', description: '恢复专注力', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E8%AF%BE%E9%97%B4%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E7%99%BD%E5%99%AA%E9%9F%B3%20%2B%20%E9%97%AD%E7%9C%BC', priceType: ContentPriceType.free),
      ContentItem(id: 'student_relax_4', title: '冥想入门：5 分钟呼吸', description: '学生版', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E5%86%A5%E6%83%B3%E5%85%A5%E9%97%A8%EF%BC%9A5%20%E5%88%86%E9%92%9F%E5%91%BC%E5%90%B8', priceType: ContentPriceType.free),
      ContentItem(id: 'student_relax_5', title: '番茄钟：学 25 休 5', description: '经典时间管理', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.card, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E7%95%AA%E8%8C%84%E9%92%9F%EF%BC%9A%E5%AD%A6%2025%20%E4%BC%91%205', priceType: ContentPriceType.free),
      ContentItem(id: 'student_relax_6', title: '正念写作：5 分钟写日记', description: '整理情绪', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E6%AD%A3%E5%BF%B5%E5%86%99%E4%BD%9C%EF%BC%9A5%20%E5%88%86%E9%92%9F%E5%86%99%E6%97%A5%E8%AE%B0', priceType: ContentPriceType.free),
    ],
    'student_workout': [
      ContentItem(id: 'student_workout_1', title: '课间 5 分钟：眼保健操 + 拉伸', description: '5 个 1 分钟动作', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E8%AF%BE%E9%97%B4%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E7%9C%BC%E4%BF%9D%E5%81%A5%E6%93%8D%20%2B%20%E6%8B%89%E4%BC%B8', priceType: ContentPriceType.free),
      ContentItem(id: 'student_workout_2', title: '学生桌椅 5 分钟拉伸', description: '改善久坐', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E5%AD%A6%E7%94%9F%E6%A1%8C%E6%A4%85%205%20%E5%88%86%E9%92%9F%E6%8B%89%E4%BC%B8', priceType: ContentPriceType.free),
      ContentItem(id: 'student_workout_3', title: '中考体育：5 分钟体能', description: '立定跳远训练', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E4%B8%AD%E8%80%83%E4%BD%93%E8%82%B2%EF%BC%9A5%20%E5%88%86%E9%92%9F%E4%BD%93%E8%83%BD', priceType: ContentPriceType.free),
      ContentItem(id: 'student_workout_4', title: '跑步前后：5 分钟热身', description: '避免受伤', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E8%B7%91%E6%AD%A5%E5%89%8D%E5%90%8E%EF%BC%9A5%20%E5%88%86%E9%92%9F%E7%83%AD%E8%BA%AB', priceType: ContentPriceType.free),
      ContentItem(id: 'student_workout_5', title: '学生减压操：5 分钟', description: '跳一跳', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E5%AD%A6%E7%94%9F%E5%87%8F%E5%8E%8B%E6%93%8D%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'student_workout_6', title: '握笔手疲劳：5 分钟手指操', description: '中考写字前', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E6%8F%A1%E7%AC%94%E6%89%8B%E7%96%B2%E5%8A%B3%EF%BC%9A5%20%E5%88%86%E9%92%9F%E6%89%8B%E6%8C%87%E6%93%8D', priceType: ContentPriceType.free),
    ],

    // 上班族 (4-6 条/key)
    'officeWorker_learn': [
      ContentItem(id: 'officeWorker_learn_1', title: '5 分钟读懂：OKR 和 KPI 的区别', description: '职场必学概念', source: '36氪', sourceType: ContentSource.news36kr, contentType: ContentType.card, duration: '5min', externalUrl: 'https://36kr.com/search/articles/5%20%E5%88%86%E9%92%9F%E8%AF%BB%E6%87%82%EF%BC%9AOKR%20%E5%92%8C%20KPI', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_learn_2', title: '深度工作法：5 分钟入门', description: 'Cal Newport 经典方法', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://zhuanlan.zhihu.com/p/ow-2', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_learn_3', title: '怎么跟老板谈加薪？3 步走', description: '职场技能', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '8min', externalUrl: 'https://zhuanlan.zhihu.com/p/ow-3', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_learn_4', title: '金字塔原理：5 分钟入门', description: '麦肯锡方法', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://zhuanlan.zhihu.com/p/ow-4', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_learn_5', title: '高效会议：5 个减半规则', description: '职场技能', source: '36氪', sourceType: ContentSource.news36kr, contentType: ContentType.card, duration: '5min', externalUrl: 'https://36kr.com/search/articles/%E9%AB%98%E6%95%88%E4%BC%9A%E8%AE%AE%EF%BC%9A5%20%E4%B8%AA%E5%87%8F%E5%8D%8A%E8%A7%84%E5%88%99', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_learn_6', title: '向上管理：5 分钟读懂', description: '汇报技巧', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://zhuanlan.zhihu.com/p/ow-6', priceType: ContentPriceType.free),
    ],
    'officeWorker_listen': [
      ContentItem(id: 'officeWorker_listen_1', title: '通勤要闻：5 分钟早报', description: '今日 3 条要闻', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E9%80%9A%E5%8B%A4%E8%A6%81%E9%97%BB%EF%BC%9A5%20%E5%88%86%E9%92%9F%E6%97%A9%E6%8A%A5', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_listen_2', title: '行业动态：AI 周报', description: '这周 AI 圈发生了什么', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '10min', externalUrl: 'https://www.ximalaya.com/search/%E8%A1%8C%E4%B8%9A%E5%8A%A8%E6%80%81%EF%BC%9AAI%20%E5%91%A8%E6%8A%A5', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_listen_3', title: '36 氪开氪：5 分钟商业洞察', description: '深度分析', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/36%20%E6%B0%AA%E5%BC%80%E6%B0%AA%EF%BC%9A5%20%E5%88%86%E9%92%9F%E5%95%86%E4%B8%9A%E6%B4%9E%E5%AF%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_listen_4', title: '哈佛商业评论：5 分钟', description: '管理经典', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E5%93%88%E4%BD%9B%E5%95%86%E4%B8%9A%E8%AF%84%E8%AE%BA%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_listen_5', title: '得到头条：5 分钟', description: '通勤精选', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E5%BE%97%E5%88%B0%E5%A4%B4%E6%9D%A1%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_listen_6', title: '樊登读书：5 分钟', description: '一本书的精华', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E6%A8%8A%E7%99%BB%E8%AF%BB%E4%B9%A6%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
    ],
    'officeWorker_relax': [
      ContentItem(id: 'officeWorker_relax_1', title: '午休 5 分钟正念', description: '闭眼 + 呼吸', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://zhuanlan.zhihu.com/p/ow-relax-1', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_relax_2', title: '下班后：5 分钟清空大脑', description: '心理学家方法', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://zhuanlan.zhihu.com/p/ow-relax-2', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_relax_3', title: '通勤路上：白噪音 + 闭眼', description: '5 分钟', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E9%80%9A%E5%8B%A4%E8%B7%AF%E4%B8%8A%EF%BC%9A%E7%99%BD%E5%99%AA%E9%9F%B3%20%2B%20%E9%97%AD%E7%9C%BC', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_relax_4', title: '5 分钟办公室冥想', description: '耳机版', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/5%20%E5%88%86%E9%92%9F%E5%8A%9E%E5%85%AC%E5%AE%A4%E5%86%A5%E6%83%B3', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_relax_5', title: '睡前 5 分钟：5 个深呼吸', description: '改善睡眠', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://zhuanlan.zhihu.com/p/ow-relax-5', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_relax_6', title: '周末：5 分钟做计划', description: '下周一不慌', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.card, duration: '5min', externalUrl: 'https://zhuanlan.zhihu.com/p/ow-relax-6', priceType: ContentPriceType.free),
    ],
    'officeWorker_workout': [
      ContentItem(id: 'officeWorker_workout_1', title: '工位 5 分钟：颈肩放松', description: '5 个动作，告别酸痛', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E5%B7%A5%E4%BD%8D%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E9%A2%88%E8%82%A9%E6%94%BE%E6%9D%BE', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_workout_2', title: '办公室 5 分钟：腰背拉伸', description: '久坐救星', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E5%8A%9E%E5%85%AC%E5%AE%A4%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E8%85%B0%E8%83%8C%E6%8B%89%E4%BC%B8', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_workout_3', title: '电脑前 5 分钟：手腕保健', description: '防鼠标手', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E7%94%B5%E8%84%91%E5%89%8D%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E6%89%8B%E8%85%95%E4%BF%9D%E5%81%A5', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_workout_4', title: '会议室后：5 分钟站立体操', description: '提神', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E4%BC%9A%E8%AE%AE%E5%AE%A4%E5%90%8E%EF%BC%9A5%20%E5%88%86%E9%92%9F%E7%AB%99%E7%AB%8B%E4%BD%93%E6%93%8D', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_workout_5', title: '加班前 5 分钟：眼保健操', description: '防视疲劳', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E5%8A%A0%E7%8F%AD%E5%89%8D%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E7%9C%BC%E4%BF%9D%E5%81%A5%E6%93%8D', priceType: ContentPriceType.free),
      ContentItem(id: 'officeWorker_workout_6', title: '下班前 5 分钟：坐姿调整', description: '缓解久坐', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E4%B8%8B%E7%8F%AD%E5%89%8D%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E5%9D%90%E5%A7%BF%E8%B0%83%E6%95%B4', priceType: ContentPriceType.free),
    ],

    // 创业者
    'entrepreneur_learn': [
      ContentItem(id: 'entrepreneur_learn_1', title: '5 分钟读懂：精益创业 MVP', description: 'Eric Ries 经典方法', source: '36氪', sourceType: ContentSource.news36kr, contentType: ContentType.card, duration: '5min', externalUrl: 'https://36kr.com/search/articles/5%20%E5%88%86%E9%92%9F%E8%AF%BB%E6%87%82%EF%BC%9A%E7%B2%BE%E7%9B%8A%E5%88%9B%E4%B8%9A%20MVP', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_learn_2', title: '商业案例：瑞幸怎么翻盘的', description: '深度分析', source: '36氪', sourceType: ContentSource.news36kr, contentType: ContentType.card, duration: '8min', externalUrl: 'https://36kr.com/search/articles/%E5%95%86%E4%B8%9A%E6%A1%88%E4%BE%8B%EF%BC%9A%E7%91%9E%E5%B9%B8%E6%80%8E%E4%B9%88%E7%BF%BB%E7%9B%98%E7%9A%84', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_learn_3', title: '融资谈判：3 个关键条款', description: 'Term Sheet 入门', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '10min', externalUrl: 'https://zhuanlan.zhihu.com/p/ent-3', priceType: ContentPriceType.membership, priceNote: '盐选会员免费读'),
      ContentItem(id: 'entrepreneur_learn_4', title: 'OKR 实战：5 分钟模板', description: '创业公司专属', source: '36氪', sourceType: ContentSource.news36kr, contentType: ContentType.card, duration: '5min', externalUrl: 'https://36kr.com/search/articles/OKR%20%E5%AE%9E%E6%88%98%EF%BC%9A5%20%E5%88%86%E9%92%9F%E6%A8%A1%E6%9D%BF', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_learn_5', title: '5 分钟读懂：增长黑客', description: 'Sean Ellis 方法', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://zhuanlan.zhihu.com/p/ent-5', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_learn_6', title: '失败案例：5 分钟复盘', description: 'WeWork / 瑞幸', source: '36氪', sourceType: ContentSource.news36kr, contentType: ContentType.card, duration: '5min', externalUrl: 'https://36kr.com/search/articles/%E5%A4%B1%E8%B4%A5%E6%A1%88%E4%BE%8B%EF%BC%9A5%20%E5%88%86%E9%92%9F%E5%A4%8D%E7%9B%98', priceType: ContentPriceType.free),
    ],
    'entrepreneur_listen': [
      ContentItem(id: 'entrepreneur_listen_1', title: '商业要闻 5 分钟', description: '今日 3 条要闻', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E5%95%86%E4%B8%9A%E8%A6%81%E9%97%BB%205%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_listen_2', title: 'YC 创业课：5 分钟', description: '硅谷方法', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/YC%20%E5%88%9B%E4%B8%9A%E8%AF%BE%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_listen_3', title: '一级市场：5 分钟看融资', description: 'IT 桔子', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E4%B8%80%E7%BA%A7%E5%B8%82%E5%9C%BA%EF%BC%9A5%20%E5%88%86%E9%92%9F%E7%9C%8B%E8%9E%8D%E8%B5%84', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_listen_4', title: '科技早报：5 分钟', description: '虎嗅', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E7%A7%91%E6%8A%80%E6%97%A9%E6%8A%A5%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_listen_5', title: '投资人访谈：5 分钟', description: '经纬创投', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E6%8A%95%E8%B5%84%E4%BA%BA%E8%AE%BF%E8%B0%88%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_listen_6', title: '出海公司：5 分钟 case', description: 'SHEIN/TikTok', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E5%87%BA%E6%B5%B7%E5%85%AC%E5%8F%B8%EF%BC%9A5%20%E5%88%86%E9%92%9F%20case', priceType: ContentPriceType.free),
    ],
    'entrepreneur_relax': [
      ContentItem(id: 'entrepreneur_relax_1', title: '决策疲劳：5 分钟恢复', description: '创始人专属', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://zhuanlan.zhihu.com/p/ent-relax-1', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_relax_2', title: '焦虑时 5 分钟：呼吸 + 记录', description: 'CBT 方法', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://zhuanlan.zhihu.com/p/ent-relax-2', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_relax_3', title: '凌晨 3 点 5 分钟：CEO 冥想', description: '特别版', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E5%87%8C%E6%99%A8%203%20%E7%82%B9%205%20%E5%88%86%E9%92%9F%EF%BC%9ACEO%20', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_relax_4', title: '5 分钟高能量充电', description: '5 个动作', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=5%20%E5%88%86%E9%92%9F%E9%AB%98%E8%83%BD%E9%87%8F%E5%85%85%E7%94%B5', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_relax_5', title: '周末不加班：5 分钟计划', description: '下周一不慌', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://zhuanlan.zhihu.com/p/ent-relax-5', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_relax_6', title: '会议间隙 5 分钟：白噪音', description: '恢复专注', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E4%BC%9A%E8%AE%AE%E9%97%B4%E9%9A%99%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E7%99%BD%E5%99%AA%E9%9F%B3', priceType: ContentPriceType.free),
    ],
    'entrepreneur_workout': [
      ContentItem(id: 'entrepreneur_workout_1', title: '出差间隙 5 分钟：徒手训练', description: '酒店房间可做', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E5%87%BA%E5%B7%AE%E9%97%B4%E9%9A%99%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E5%BE%92%E6%89%8B%E8%AE%AD%E7%BB%83', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_workout_2', title: '会议室后 5 分钟：拉伸', description: '久坐救星', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E4%BC%9A%E8%AE%AE%E5%AE%A4%E5%90%8E%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E6%8B%89%E4%BC%B8', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_workout_3', title: '打车 5 分钟：颈肩放松', description: '通勤做', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E6%89%93%E8%BD%A6%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E9%A2%88%E8%82%A9%E6%94%BE%E6%9D%BE', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_workout_4', title: '见客户前 5 分钟：提神操', description: '咖啡替代', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E8%A7%81%E5%AE%A2%E6%88%B7%E5%89%8D%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E6%8F%90%E7%A5%9E%E6%93%8D', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_workout_5', title: '加班前 5 分钟：眼保健', description: '防视疲劳', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E5%8A%A0%E7%8F%AD%E5%89%8D%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E7%9C%BC%E4%BF%9D%E5%81%A5', priceType: ContentPriceType.free),
      ContentItem(id: 'entrepreneur_workout_6', title: '出差高铁 5 分钟：坐姿操', description: '避免腰疼', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E5%87%BA%E5%B7%AE%E9%AB%98%E9%93%81%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E5%9D%90%E5%A7%BF%E6%93%8D', priceType: ContentPriceType.free),
    ],

    // 宝爸宝妈
    'parent_learn': [
      ContentItem(id: 'parent_learn_1', title: '5 分钟学：跟孩子好好说话', description: '非暴力沟通', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=5%20%E5%88%86%E9%92%9F%E5%AD%A6%EF%BC%9A%E8%B7%9F%E5%AD%A9%E5%AD%90%E5%A5%BD%E5%A5%BD%E8%AF%B4%E8%AF%9D', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_learn_2', title: '孩子写作业磨蹭？3 步搞定', description: '实用方法', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '8min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E5%AD%A9%E5%AD%90%E5%86%99%E4%BD%9C%E4%B8%9A%E7%A3%A8%E8%B9%AD%EF%BC%9F3%20%E6%AD%A5%E6%90%9E%E5%AE%9A', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_learn_3', title: '宝爸宝妈：5 分钟时间管理', description: '碎片时间育儿', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E5%AE%9D%E7%88%B8%E5%AE%9D%E5%A6%88%EF%BC%9A5%20%E5%88%86%E9%92%9F%E6%97%B6%E9%97%B4%E7%AE%A1%E7%90%86', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_learn_4', title: '5 分钟读懂：正面管教', description: 'Jane Nelsen 方法', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=5%20%E5%88%86%E9%92%9F%E8%AF%BB%E6%87%82%EF%BC%9A%E6%AD%A3%E9%9D%A2%E7%AE%A1%E6%95%99', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_learn_5', title: '孩子哭闹：5 分钟冷静法', description: '心理学方法', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E5%AD%A9%E5%AD%90%E5%93%AD%E9%97%B9%EF%BC%9A5%20%E5%88%86%E9%92%9F%E5%86%B7%E9%9D%99%E6%B3%95', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_learn_6', title: '电子产品：5 分钟立规矩', description: '实用方法', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.card, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E7%94%B5%E5%AD%90%E4%BA%A7%E5%93%81%EF%BC%9A5%20%E5%88%86%E9%92%9F%E7%AB%8B%E8%A7%84%E7%9F%A9', priceType: ContentPriceType.free),
    ],
    'parent_listen': [
      ContentItem(id: 'parent_listen_1', title: '亲子小故事：5 分钟', description: '宝宝也能听', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E4%BA%B2%E5%AD%90%E5%B0%8F%E6%95%85%E4%BA%8B%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_listen_2', title: '晚安妈妈：5 分钟童谣', description: '哄睡专用', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E6%99%9A%E5%AE%89%E5%A6%88%E5%A6%88%EF%BC%9A5%20%E5%88%86%E9%92%9F%E7%AB%A5%E8%B0%A3', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_listen_3', title: '凯叔讲故事：5 分钟', description: '经典', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E5%87%AF%E5%8F%94%E8%AE%B2%E6%95%85%E4%BA%8B%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_listen_4', title: '宝宝早教：5 分钟音乐', description: '0-3 岁', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E5%AE%9D%E5%AE%9D%E6%97%A9%E6%95%99%EF%BC%9A5%20%E5%88%86%E9%92%9F%E9%9F%B3%E4%B9%90', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_listen_5', title: '胎教音乐：5 分钟', description: '孕期', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E8%83%8E%E6%95%99%E9%9F%B3%E4%B9%90%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_listen_6', title: '育儿专家：5 分钟答疑', description: '崔玉涛 / 张思莱', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E8%82%B2%E5%84%BF%E4%B8%93%E5%AE%B6%EF%BC%9A5%20%E5%88%86%E9%92%9F%E7%AD%94%E7%96%91', priceType: ContentPriceType.free),
    ],
    'parent_relax': [
      ContentItem(id: 'parent_relax_1', title: '宝妈的 5 分钟自我对话', description: '喘口气', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E5%AE%9D%E5%A6%88%E7%9A%84%205%20%E5%88%86%E9%92%9F%E8%87%AA%E6%88%91%E5%AF%B9%E8%AF%9D', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_relax_2', title: '5 分钟：宝宝睡后妈妈冥想', description: '专属', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/5%20%E5%88%86%E9%92%9F%EF%BC%9A%E5%AE%9D%E5%AE%9D%E7%9D%A1%E5%90%8E%E5%A6%88%E5%A6%88%E5%86%A5%E6%83%B3', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_relax_3', title: '凌晨喂奶 5 分钟：正念', description: '特别版', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E5%87%8C%E6%99%A8%E5%96%82%E5%A5%B6%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E6%AD%A3%E5%BF%B5', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_relax_4', title: '5 分钟：拒绝妈妈内疚', description: '心理学', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=5%20%E5%88%86%E9%92%9F%EF%BC%9A%E6%8B%92%E7%BB%9D%E5%A6%88%E5%A6%88%E5%86%85%E7%96%9A', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_relax_5', title: '周末 5 分钟：妈妈独处', description: '必备', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.card, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E5%91%A8%E6%9C%AB%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E5%A6%88%E5%A6%88%E7%8B%AC%E5%A4%84', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_relax_6', title: '宝爸 5 分钟：陪玩不烦躁', description: '心理学', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E5%AE%9D%E7%88%B8%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E9%99%AA%E7%8E%A9%E4%B8%8D%E7%83%A6%E8%BA%81', priceType: ContentPriceType.free),
    ],
    'parent_workout': [
      ContentItem(id: 'parent_workout_1', title: '边带娃边动：5 分钟', description: '客厅微运动', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E8%BE%B9%E5%B8%A6%E5%A8%83%E8%BE%B9%E5%8A%A8%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_workout_2', title: '宝宝睡了 5 分钟：核心训练', description: '恢复身材', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E5%AE%9D%E5%AE%9D%E7%9D%A1%E4%BA%86%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E6%A0%B8%E5%BF%83%E8%AE%AD%E7%BB%83', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_workout_3', title: '推婴儿车 5 分钟：快步走', description: '户外', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E6%8E%A8%E5%A9%B4%E5%84%BF%E8%BD%A6%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E5%BF%AB%E6%AD%A5%E8%B5%B0', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_workout_4', title: '5 分钟产后恢复：凯格尔', description: '妈妈专属', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=5%20%E5%88%86%E9%92%9F%E4%BA%A7%E5%90%8E%E6%81%A2%E5%A4%8D%EF%BC%9A%E5%87%AF%E6%A0%BC%E5%B0%94', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_workout_5', title: '宝爸 5 分钟：腰背训练', description: '抱娃救星', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E5%AE%9D%E7%88%B8%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E8%85%B0%E8%83%8C%E8%AE%AD%E7%BB%83', priceType: ContentPriceType.free),
      ContentItem(id: 'parent_workout_6', title: '周末 5 分钟：亲子瑜伽', description: '一起做', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E5%91%A8%E6%9C%AB%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E4%BA%B2%E5%AD%90%E7%91%9C%E4%BC%BD', priceType: ContentPriceType.free),
    ],

    // 退休人群
    'senior_learn': [
      ContentItem(id: 'senior_learn_1', title: '老年人如何预防高血压？', description: '5 分钟讲清', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E8%80%81%E5%B9%B4%E4%BA%BA%E5%A6%82%E4%BD%95%E9%A2%84%E9%98%B2%E9%AB%98%E8%A1%80%E5%8E%8B%EF%BC%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_learn_2', title: '膝盖保养：日常 3 个动作', description: '医生推荐', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '8min', externalUrl: 'https://search.bilibili.com/all?keyword=%E8%86%9D%E7%9B%96%E4%BF%9D%E5%85%BB%EF%BC%9A%E6%97%A5%E5%B8%B8%203%20%E4%B8%AA%E5%8A%A8%E4%BD%9C', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_learn_3', title: '糖尿病前期如何逆转？', description: '5 分钟健康课', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E7%B3%96%E5%B0%BF%E7%97%85%E5%89%8D%E6%9C%9F%E5%A6%82%E4%BD%95%E9%80%86%E8%BD%AC%EF%BC%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_learn_4', title: '骨质疏松：5 分钟讲清', description: '中老年必知', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E9%AA%A8%E8%B4%A8%E7%96%8F%E6%9D%BE%EF%BC%9A5%20%E5%88%86%E9%92%9F%E8%AE%B2%E6%B8%85', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_learn_5', title: '5 分钟学会看体检报告', description: '关键指标', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.card, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=5%20%E5%88%86%E9%92%9F%E5%AD%A6%E4%BC%9A%E7%9C%8B%E4%BD%93%E6%A3%80%E6%8A%A5%E5%91%8A', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_learn_6', title: '防跌倒：5 分钟家庭改造', description: '实用', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E9%98%B2%E8%B7%8C%E5%80%92%EF%BC%9A5%20%E5%88%86%E9%92%9F%E5%AE%B6%E5%BA%AD%E6%94%B9%E9%80%A0', priceType: ContentPriceType.free),
    ],
    'senior_listen': [
      ContentItem(id: 'senior_listen_1', title: '今日要闻 5 分钟', description: '温和语气播报', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E4%BB%8A%E6%97%A5%E8%A6%81%E9%97%BB%205%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_listen_2', title: '老歌回顾：5 分钟', description: '怀旧金曲', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E8%80%81%E6%AD%8C%E5%9B%9E%E9%A1%BE%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_listen_3', title: '养生堂：5 分钟', description: '北京卫视', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E5%85%BB%E7%94%9F%E5%A0%82%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_listen_4', title: '相声 5 分钟：笑一笑', description: '郭德纲', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E7%9B%B8%E5%A3%B0%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E7%AC%91%E4%B8%80%E7%AC%91', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_listen_5', title: '评书 5 分钟：三国', description: '袁阔成', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E8%AF%84%E4%B9%A6%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E4%B8%89%E5%9B%BD', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_listen_6', title: '健康讲座 5 分钟', description: '协和医院', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E5%81%A5%E5%BA%B7%E8%AE%B2%E5%BA%A7%205%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
    ],
    'senior_relax': [
      ContentItem(id: 'senior_relax_1', title: '正念呼吸：5 分钟', description: '温和引导', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E6%AD%A3%E5%BF%B5%E5%91%BC%E5%90%B8%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_relax_2', title: '5 分钟：午休白噪音', description: '鸟鸣 + 流水', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/5%20%E5%88%86%E9%92%9F%EF%BC%9A%E5%8D%88%E4%BC%91%E7%99%BD%E5%99%AA%E9%9F%B3', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_relax_3', title: '5 分钟：睡前放松', description: '改善失眠', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/5%20%E5%88%86%E9%92%9F%EF%BC%9A%E7%9D%A1%E5%89%8D%E6%94%BE%E6%9D%BE', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_relax_4', title: '5 分钟：八段锦呼吸', description: '中医', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=5%20%E5%88%86%E9%92%9F%EF%BC%9A%E5%85%AB%E6%AE%B5%E9%94%A6%E5%91%BC%E5%90%B8', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_relax_5', title: '5 分钟：冥想入门', description: '老年版', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=5%20%E5%88%86%E9%92%9F%EF%BC%9A%E5%86%A5%E6%83%B3%E5%85%A5%E9%97%A8', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_relax_6', title: '5 分钟：园艺冥想', description: '专属', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=5%20%E5%88%86%E9%92%9F%EF%BC%9A%E5%9B%AD%E8%89%BA%E5%86%A5%E6%83%B3', priceType: ContentPriceType.free),
    ],
    'senior_workout': [
      ContentItem(id: 'senior_workout_1', title: '温和拉伸：5 个动作', description: '每个 1 分钟', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '8min', externalUrl: 'https://search.bilibili.com/all?keyword=%E6%B8%A9%E5%92%8C%E6%8B%89%E4%BC%B8%EF%BC%9A5%20%E4%B8%AA%E5%8A%A8%E4%BD%9C', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_workout_2', title: '5 分钟：太极入门', description: '24 式', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=5%20%E5%88%86%E9%92%9F%EF%BC%9A%E5%A4%AA%E6%9E%81%E5%85%A5%E9%97%A8', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_workout_3', title: '5 分钟：八段锦', description: '中医传统', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=5%20%E5%88%86%E9%92%9F%EF%BC%9A%E5%85%AB%E6%AE%B5%E9%94%A6', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_workout_4', title: '5 分钟：关节操', description: '肩颈腰膝', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=5%20%E5%88%86%E9%92%9F%EF%BC%9A%E5%85%B3%E8%8A%82%E6%93%8D', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_workout_5', title: '5 分钟：走路健身法', description: '日常', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=5%20%E5%88%86%E9%92%9F%EF%BC%9A%E8%B5%B0%E8%B7%AF%E5%81%A5%E8%BA%AB%E6%B3%95', priceType: ContentPriceType.free),
      ContentItem(id: 'senior_workout_6', title: '5 分钟：椅子操', description: '久坐救星', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=5%20%E5%88%86%E9%92%9F%EF%BC%9A%E6%A4%85%E5%AD%90%E6%93%8D', priceType: ContentPriceType.free),
    ],

    // 儿童（6-12 岁）— 宪法 §4 必做
    'child_learn': [
      ContentItem(id: 'child_learn_1', title: '为什么天空是蓝色的？', description: '用故事讲科学', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E4%B8%BA%E4%BB%80%E4%B9%88%E5%A4%A9%E7%A9%BA%E6%98%AF%E8%93%9D%E8%89%B2%E7%9A%84%EF%BC%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'child_learn_2', title: '小实验：会跳舞的葡萄干', description: '在家能做', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '3min', externalUrl: 'https://search.bilibili.com/all?keyword=%E5%B0%8F%E5%AE%9E%E9%AA%8C%EF%BC%9A%E4%BC%9A%E8%B7%B3%E8%88%9E%E7%9A%84%E8%91%A1%E8%90%84%E5%B9%B2', priceType: ContentPriceType.free),
      ContentItem(id: 'child_learn_3', title: '十万个为什么：动物会做梦吗？', description: '趣味科普', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '3min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E5%8D%81%E4%B8%87%E4%B8%AA%E4%B8%BA%E4%BB%80%E4%B9%88%EF%BC%9A%E5%8A%A8%E7%89%A9%E4%BC%9A%E5%81%9A%E6%A2%A6%E5%90%97%EF%BC%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'child_learn_4', title: '恐龙为什么灭绝？5 分钟讲清', description: '百科', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E6%81%90%E9%BE%99%E4%B8%BA%E4%BB%80%E4%B9%88%E7%81%AD%E7%BB%9D%EF%BC%9F5%20%E5%88%86%E9%92%9F%E8%AE%B2%E6%B8%85', priceType: ContentPriceType.free),
      ContentItem(id: 'child_learn_5', title: '为什么星星会眨眼？', description: '天文入门', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E4%B8%BA%E4%BB%80%E4%B9%88%E6%98%9F%E6%98%9F%E4%BC%9A%E7%9C%A8%E7%9C%BC%EF%BC%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'child_learn_6', title: '古诗 5 分钟：鹅鹅鹅', description: '经典启蒙', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '3min', externalUrl: 'https://search.bilibili.com/all?keyword=%E5%8F%A4%E8%AF%97%205%20%E5%88%86%E9%92%9F%EF%BC%9A%E9%B9%85%E9%B9%85%E9%B9%85', priceType: ContentPriceType.free),
    ],
    'child_listen': [
      ContentItem(id: 'child_listen_1', title: '睡前故事：小熊的森林', description: '5 分钟温馨', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E7%9D%A1%E5%89%8D%E6%95%85%E4%BA%8B%EF%BC%9A%E5%B0%8F%E7%86%8A%E7%9A%84%E6%A3%AE%E6%9E%97', priceType: ContentPriceType.free),
      ContentItem(id: 'child_listen_2', title: '成语故事：5 分钟', description: '学一个成语', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E6%88%90%E8%AF%AD%E6%95%85%E4%BA%8B%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'child_listen_3', title: '小猪佩奇：5 分钟', description: '经典 IP', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E5%B0%8F%E7%8C%AA%E4%BD%A9%E5%A5%87%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'child_listen_4', title: '西游记：5 分钟一段', description: '经典启蒙', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E8%A5%BF%E6%B8%B8%E8%AE%B0%EF%BC%9A5%20%E5%88%86%E9%92%9F%E4%B8%80%E6%AE%B5', priceType: ContentPriceType.free),
      ContentItem(id: 'child_listen_5', title: '英文儿歌：5 分钟', description: '磨耳朵', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E8%8B%B1%E6%96%87%E5%84%BF%E6%AD%8C%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
      ContentItem(id: 'child_listen_6', title: '三国演义儿童版：5 分钟', description: '启蒙故事', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/%E4%B8%89%E5%9B%BD%E6%BC%94%E4%B9%89%E5%84%BF%E7%AB%A5%E7%89%88%EF%BC%9A5%20%E5%88%86%E9%92%9F', priceType: ContentPriceType.free),
    ],
    'child_relax': [
      ContentItem(id: 'child_relax_1', title: '深呼吸想象：飞在云上', description: '温和引导', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=%E6%B7%B1%E5%91%BC%E5%90%B8%E6%83%B3%E8%B1%A1%EF%BC%9A%E9%A3%9E%E5%9C%A8%E4%BA%91%E4%B8%8A', priceType: ContentPriceType.free),
      ContentItem(id: 'child_relax_2', title: '5 分钟：考完试不紧张', description: '心理学', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=5%20%E5%88%86%E9%92%9F%EF%BC%9A%E8%80%83%E5%AE%8C%E8%AF%95%E4%B8%8D%E7%B4%A7%E5%BC%A0', priceType: ContentPriceType.free),
      ContentItem(id: 'child_relax_3', title: '5 分钟：睡前放松故事', description: '哄睡', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/5%20%E5%88%86%E9%92%9F%EF%BC%9A%E7%9D%A1%E5%89%8D%E6%94%BE%E6%9D%BE%E6%95%85%E4%BA%8B', priceType: ContentPriceType.free),
      ContentItem(id: 'child_relax_4', title: '5 分钟：心情不好说出来', description: '情绪管理', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=5%20%E5%88%86%E9%92%9F%EF%BC%9A%E5%BF%83%E6%83%85%E4%B8%8D%E5%A5%BD%E8%AF%B4%E5%87%BA%E6%9D%A5', priceType: ContentPriceType.free),
      ContentItem(id: 'child_relax_5', title: '5 分钟：彩虹呼吸', description: '儿童版', source: '喜马拉雅', sourceType: ContentSource.ximalaya, contentType: ContentType.audio, duration: '5min', externalUrl: 'https://www.ximalaya.com/search/5%20%E5%88%86%E9%92%9F%EF%BC%9A%E5%BD%A9%E8%99%B9%E5%91%BC%E5%90%B8', priceType: ContentPriceType.free),
      ContentItem(id: 'child_relax_6', title: '5 分钟：写日记', description: '整理心情', source: '知乎', sourceType: ContentSource.zhihu, contentType: ContentType.article, duration: '5min', externalUrl: 'https://www.zhihu.com/search?type=content&q=5%20%E5%88%86%E9%92%9F%EF%BC%9A%E5%86%99%E6%97%A5%E8%AE%B0', priceType: ContentPriceType.free),
    ],
    'child_workout': [
      ContentItem(id: 'child_workout_1', title: '课间游戏：5 个安全动作', description: '像玩游戏', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=%E8%AF%BE%E9%97%B4%E6%B8%B8%E6%88%8F%EF%BC%9A5%20%E4%B8%AA%E5%AE%89%E5%85%A8%E5%8A%A8%E4%BD%9C', priceType: ContentPriceType.free),
      ContentItem(id: 'child_workout_2', title: '5 分钟：跳绳入门', description: '小学体育', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=5%20%E5%88%86%E9%92%9F%EF%BC%9A%E8%B7%B3%E7%BB%B3%E5%85%A5%E9%97%A8', priceType: ContentPriceType.free),
      ContentItem(id: 'child_workout_3', title: '5 分钟：体能训练', description: '跳远 + 跑步', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=5%20%E5%88%86%E9%92%9F%EF%BC%9A%E4%BD%93%E8%83%BD%E8%AE%AD%E7%BB%83', priceType: ContentPriceType.free),
      ContentItem(id: 'child_workout_4', title: '5 分钟：眼保健操', description: '近视预防', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=5%20%E5%88%86%E9%92%9F%EF%BC%9A%E7%9C%BC%E4%BF%9D%E5%81%A5%E6%93%8D', priceType: ContentPriceType.free),
      ContentItem(id: 'child_workout_5', title: '5 分钟：舞蹈入门', description: '儿童版', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=5%20%E5%88%86%E9%92%9F%EF%BC%9A%E8%88%9E%E8%B9%88%E5%85%A5%E9%97%A8', priceType: ContentPriceType.free),
      ContentItem(id: 'child_workout_6', title: '5 分钟：科学坐姿操', description: '防驼背', source: 'B站', sourceType: ContentSource.bilibili, contentType: ContentType.video, videoPlatform: VideoPlatform.bilibili, duration: '5min', externalUrl: 'https://search.bilibili.com/all?keyword=5%20%E5%88%86%E9%92%9F%EF%BC%9A%E7%A7%91%E5%AD%A6%E5%9D%90%E5%A7%BF%E6%93%8D', priceType: ContentPriceType.free),
    ],
  };
}
